[profile.release]
opt-level = 3
lto = true
panic = "abort"
codegen-units = 1
strip = true

[package]
name = "graph_generation"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
